### ISSUE TITLE
Initial Pointer Tensor Support

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#1695]
Part of Epic: https://github.com/OpenMined/PySyft/issues/1657

You should extend torch.Tensor with the following operation
- [x] .create_pointer() which initializes a pointer to this tensor. #1696
- [x] .serialize() which serializes the current tensor to a serialized format AND .deserialize() #1694 
- [x] .send() which creates a pointer and sends a serialized version of "self" to the correct worker  #1697

In this project, you should create a basic pointer tensor object which is capable of the following operations:
- [x] .get() which moves the data being pointed to to the local machine #1698

After .send() and .get() are working, we should add support for:
- [x] initial garbage collection (.__del__ overloading) support for PointerTensor objects and the objects they point to. #1701 

While sending and getting tensors, Issue #1729 should be considered, namely should we keep empty head (see issue) when we send tensors. If there is no example where this would be a problem, heads will be removed.

Additional Acceptance Criteria:
- [x] unit tests should test sending receiving tensors of all types
- [ ] initialize the "tutorials" folder with a notebook showing how to send/receive tensors.

**Comment by kamathhrishi** [comment]
I guess we need to first finish having notebooks that demonstrates sending and receiving tensors for which sending tensors asynchronously is a requirement ?

**Comment by LaRiffle** [comment]
I'm not sure async is a requirement, but indeed a notebook (like tutorial Part 1 on master) is missing!
