### ISSUE TITLE
Differential Privacy

### ISSUE THREAD

**Issue by jlebensold** [OpenMined/PySyft#1824]
This is an Epic which is a sub-project under the project Torch 1.0,  the specs for which you can find here (#1587)

We'd like to implement local differential privacy support at the Tensor level within PySyft.

- [x] Prototype [sensitivity tracking tensor](https://github.com/OpenMined/PySyft/blob/dev/examples/experimental/DP%20Tensor%20Experimentation%20-%20v1.ipynb)
- [x] Fix bugs in sensitivity tracking tensor (https://github.com/OpenMined/PySyft/issues/1928)
- [ ] Evaluate sensitivity on unit tests pulled from Cynthia Dwork's book (https://github.com/OpenMined/PySyft/issues/1929)
- [x] Vectorize Prototype (to use torch tensors instead of numpy tensors) (https://github.com/OpenMined/PySyft/issues/1930)
- [ ] Integrate Vectorized Prototype into PySyft (including unit tests) (https://github.com/OpenMined/PySyft/issues/1931)
- [ ] Integrate with Moment's Accountant from Abadi et al. (include unit tests checking for correctness from Abadi's implementation) (https://github.com/OpenMined/PySyft/issues/1932)
- [ ] Create DP-SGD Optimizer and use the sensitivity / accountant above (https://github.com/OpenMined/PySyft/issues/1932)
- [ ] Create FL demo with DP-SGD Optimizer (https://github.com/OpenMined/PySyft/issues/1933)

Current implementations involve using a drop-in replacement of an optimizer (e.g. SGD / ADAM):
https://github.com/tensorflow/privacy/blob/master/privacy/optimizers/dp_optimizer.py

Our approach should assume:
1. That the relationship between a worker and the Tensors that they own are trusted
2. That entities owned by different workers, when combined, may break the bounds of the privacy budget (epsilon)
3. Combining Worker-owned tensors should not enable "linkage attacks"

One way of dealing with this is for each worker to maintain a EntitySet of IDs that refer to each Tensor that it owns. 

There's an open question for how we might deal with PointerTensors since they are not owned by the same worker.

**Comment by iamtrask** [comment]
https://github.com/OpenMined/PySyft/blob/torch_1/examples/experimental/DP%20Tensor%20Experimentation%20-%20v1.ipynb

**Comment by iamtrask** [comment]
https://github.com/OpenMined/PySyft/blob/torch_1/examples/experimental/DP%20Tensor%20Experimentation%20-%20v2.ipynb
