### ISSUE TITLE
Encrypted Training using SMPC over PyTorch

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2235]
**Describe the solution you'd like**
The SMPC tensor we've implemented (AdditiveSharedTensor) works well for making prediction (see [Tutorial 11](https://github.com/OpenMined/PySyft/blob/dev/examples/tutorials/Part%2011%20-%20Secure%20Deep%20Learning%20Classification.ipynb)). We would like to extend this to perform training as well. The main pb is that we redefine operations such as multiplication and can't use the normal autograd functionality of PyTorch. We would like a way to give custom gradient functions to autograd when the differentiated operation has been redefined.

We have had exciting work around an AutogradTensor in #1902 #1942 #2095 which can be very helpful and might be and interesting starting point.

- [x] Support of more basic ops for AdditiveSharedTensor like mean / sum #2245
- [x] Add support of Zq field values #2261 
- [x] Monitor network usage #2256 
- [x] AutogradTensor for Fixed Prec and Additive Shared Tensor #2283
- [x] Architecture optimization: remove wrappers #2372
- [x] Encrypted training Demo

**Comment by IonesioJunior** [comment]
Has anyone started this anywhere? I would like to follow the development of this issue.

**Comment by robert-wagner** [comment]
@IonesioJunior @LaRiffle is taking the lead on this issue. This issue will continue to be updates as progress is made (there will be many sub issues linked here)
