### ISSUE TITLE
Additive Sharing and Fixed Precision in Zq

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2261]
This is part of #2235 

**Is your feature request related to a problem? Please describe.**
We currently allow additive sharing in the Long field, which in particular allows negative values. However the guarantees of our protocols come from the fact the values are in specific Zq fields (ie [0, 1, ..., q-1]. Therefore we should allow Fixed precision to live in Zq fields.

**Roadmap**
The steps to take to achieve this are:
- [x] add a field argument to Fixed precision
- [x] guarantee that negative values are correctly encoded, ex: -1 --> q-1
- [x] check that no overflow happens with usual operations
- [x] fix the SecureNN protocol to add the transformation of field. See https://eprint.iacr.org/2018/442.pdf Section 4.3 in particular

**Comment by Jasopaum** [comment]
I can advance on this tonight if nobody is working on it

**Comment by Jasopaum** [comment]
It seems to me like a lot is already done

**Comment by LaRiffle** [comment]
Cool feel free to start on this one!
