### ISSUE TITLE
Build a store of crypto primitives

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#2711]
**Is your feature request related to a problem? Please describe.**
Each time we need a crypto primitives (like a beaver triple), we make a (expensive) call to the crypto provider.

**Describe the solution you'd like**
We could build a sort of cache or store of crypto primitives which, based on the consumption of certain primitives, would ask for a batch of them at a time to the crypto provider. This would be made invisible to the functions which require these primitives.

- [x] Feed primitives for FSS comparison/equality #3057 
- [ ] Feed primitives for SPDZ Beaver triples WIP #3438 
- [ ] Automate consumption analysis to request dynamically the appropriate number of primitives

**Comment by deven96** [comment]
I'd like to contribute to this but the description is not quite clear
