### ISSUE TITLE
Rebooting Plans

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#2912]
**Is your feature request related to a problem? Please describe.**

At present, our implementation of Plans, Promises, and Protocols are not correct and do not integrate with each other (or with the broader stack, including the new serialization format) well. We need to re-implement this functionality (from scratch) in the following order.

**1) Implement Placeholder tensor type**, which is similar to PointerTensor except the object it refers to is hidden in .child. I.e., a placeholder's tensor chain is:

(NO Wrapper) > Placeholder > Tensor

In this way, Placeholder simply records all operations sent to the data tensor, allowing for some data conditional errors to be caught at this point. However, because it doesn't use PointerTensor, it does not engage with the insane garbage collection logic implemented around PointerTensors (which gets particularly complex when serializing and deserializing pointer tensors multiple times).

Placeholder tensors, when serialized, do not include the data tensor they contain.

**2) Rebuild Plans with the following features**: A plan's schema is

Plan Schema:
- operations: list[operations[placeholders]] - This collection of operations was recorded by tracing the plan. This is done by creating a global sy.trace parameter which, if true, records the operations that are being executed. 
- arg_placeholders: list[PlaceholderTensor]
- kwarg_placeholders: dict[string -> PlaceholderTensor]
- state_tensors: list[Tensor]

Plan Creation:
Plans are created by instantiating your input argument PlaceholderTensors, and then executing the computation graph with the sy.trace flag enabled. The list of operations for the plan can then be recovered from the global trace history.

Plan Sending:
Because we use PlaceholderTensor objects to encode the plan, plans can be serialized, sent, and deserialized without interacting with the local object store (outside of the plan itself being stored there). This should circumvent issues with garbage collection.

Remote Plan Execution:

We attach input tensors to the input argument placeholders and then run the operations as listed. When we encounter a state tensor, we wrap it to be a PlaceholderTensor before using it in the operation.

**3) Compile Plan to Torch Script**: We want the ability to take a existing plan (containing PlaceholderTensor objects) and compile it into a torch script object.

This will take the form of a method called plan.create_torchscript(*args, **kwargs) which will save the torchscript object to plan.torchscript. When creating the plan, create_torchscript happens automatically under the hood so that both the LIST version and Torchscript version of the plan are available by default at any time. 

Additionally, when running the plan, we should offer a flag which allows someone to choose which runtime they want to use (list or torchscript), which defaults to torchscript.

Note, when creating the torchscript module, the state must be passed in as an argument to the function, and the NEW state must be one of the results of the function.

- [x] https://github.com/OpenMined/PySyft/pull/2910
- [ ] https://github.com/OpenMined/PySyft/issues/2914
- [x] https://github.com/OpenMined/PySyft/issues/2915

**Comment by iamtrask** [comment]
Related: https://github.com/OpenMined/PySyft/issues/2914
