### ISSUE TITLE
Rework custom tensor types using PyTorch 1.5's support for extending `torch.tensor`

### ISSUE THREAD

**Issue by karlhigley** [OpenMined/PySyft#2991]
**Is your feature request related to a problem? Please describe.**
The current method of hooking tensors doesn't interoperate smoothly with PyTorch's JIT, which makes it difficult to impossible to convert a Torch model's backward pass to Torchscript for serialization to mobile devices.

**Describe the solution you'd like**
Rework the way tensor types are defined and hooked to use PyTorch's new affordances for extending `torch.tensor` for smoother interoperation with the JIT tracer.

**Describe alternatives you've considered**
- _Try to mash the existing code into some form that works with the JIT tracer._ We tried for a few hours and eventually decided that reworking the custom tensor types was a saner approach.
- _Build code into Plans that constructs a reverse Plan using autograd somehow._ Might be possible but doesn't account for optimization, which would still need to be Torchscript-ified somehow.

**Additional context**
Rough roadmap of the core primitives:

- [x] (PyTorch) AbstractTensor - should work with .grad, nn.Parameter, and nn.Module (including learning)
- [x] (Tensorflow) AbstractTensor - should work with Variable and Tensor
- [x] (Numpy) AbstractTensor - should work with nd.array
- [x] (Tensorlfow) AbstractVariable - should work with gradietns
- [ ] (PyTorch) AbstractParameter - should work with nn.Module
- [ ] (Tensorflow) AbstractTensor - should work with learning stuff
- [ ] (Syft) SyftTensor -> which should automatically create the above tensors in PyTorch, Tensorflow, and Numpy
- [x] FixedPrecisionTensor (a simple one) - same as before - it should inherit from SyftTensor and automatically populate the 3 frameworks
- [ ] Tensor chaining - .child should work automatically in all 3
- [ ] PointerTensor
- [ ] (Syft) PlaceholderTensor  - which should inherit from SyftTensor and automatically populate the 3 frameworks
- [ ] Plans
- [ ] Plans -> Torchscript
- [ ] Plans -> torchscript over tensor chains
- [ ] AutogradTensor shoudl allow for us to have our own python-level autograd
- [ ] Promise (which I think we should simply rename "Graph", which we can "stream" executions through)
- [ ] Protocol (same description as before)
