### ISSUE TITLE
Use Plans to send instructions to CrypTen parties

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3025]
This is major design concept that we're trying to validate: can we use Plans to ship computation instructions to CrypTen workers?

This Issue is an Epic containing:
- [x] Create a `syft.load(tensor, src=worker)` functionality #3043 
- [x] Support `syft.load` in Plans
- [x] Modify `crypten.load` to query a syft.worker
- [x] Create `syft.save` functionality and add support in Plans
- [x] Add support of some CrypTen syntax in Plans (like `t.get_plain_text()`) (see also #3026)
- [x] Run a plan using Placeholders instantiated with CrypTen Tensors #2987

**Comment by LaRiffle** [comment]
This has been completed!
