### ISSUE TITLE
Showcase privacy-preserving weighted aggregation

### ISSUE THREAD

**Issue by LaRiffle** [OpenMined/PySyft#3469]
### Idea

We propose an extension of secure aggregation which is blind weighted secure aggregation. n parties contributing their data might have unbalanced datasets, so we want to weight their contributions so data parties with datasets not appropriate for this model task will have a lower impact. So we should find the best weights for each party.
However, we want these weights to be private as well, to avoid any party to become the scapegoat.

### Proposition of roadmap
- [ ] Build a classic FL with aggregation task on MNIST where dataset are unbalanced (some only have certain classes etc) (you can use existing tutorials, but use virtual workers it will be simpler)
- [ ] Upgrade this with secure aggregation with the following SMPC technique: parties mask their contribution and the sum of all masks should sum up to 0. You do seed exchange between worker i and i - 1, worker i computes `update + mask_i - mask_(i-1)` and send this masked update to a central aggregator where all the masks for the n parties sum up to zero. 
- [ ] Upgrade to weighted secure aggregation with public weighed that you optimize at each aggregation using validation dataset owned by the aggregation (simple SGD should be fine)
- [ ] make those weights private (I can say more about this when we're there!)

**Comment by theAkhileshRai** [comment]
Interested in the project. The approach is novel. 😊

**Comment by theAkhileshRai** [comment]
Currently making the first part building classic FL aggregation task where on MNIST data where data is unbalanced.

**Comment by theAkhileshRai** [comment]
Reopening this issue as the team is working on this
