### ISSUE TITLE
0.3.1 EPIC 1: Init Basic Data Structures for Remote Execution: Workers, Clients, Actions, Messaging, ObjectStore, Pointer, etc.

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3695]
## Description
Within this epic, we will build the initial foundational data structures upon which PySyft will rely. The scope of this epic is the data structures necessary for *remote execution of arbitrary python libraries*, and thus is highly related to the Remote Execution epic which follow on this epic. Put another way, this epic will not be sufficient for remote execution, but we will have all of the foundational data structures necessary for remote execution upon the completion of this epic. The construction of each data structure (and the way in which they relate to one another) is based on the vast amount of thought-work and collective lessons learned from previous versions of PySyft.

A large portion of this work has been completed as part of 0.3.0. The remaining parts of this Ticket will be moved to 0.3.1.

## Why?
PySyft 0.2 and 0.3 have several fundamental problems with the base data structures. These problems have created an enormous amount of trickle-down technical debt. In this version, we will re-start from scratch having learned hard lessons from Syft 0.2 and 0.3. 

## Breakdown
This epic includes the following work:

- [ ]  [Initial Project Setup/Standards](https://github.com/OpenMined/PySyft/issues/3720)
- [x]  [Worker](https://github.com/OpenMined/PySyft/issues/3728)
- [x]  [Client](https://github.com/OpenMined/PySyft/issues/3729)

- [x]  [Network]()
- [x]  [Domain](https://github.com/OpenMined/PySyft/issues/3841)
- [x]  [Device]()
- [x]  [VirtualMachine](https://github.com/OpenMined/PySyft/issues/3731)

- [x]  [VirtualClient](https://github.com/OpenMined/PySyft/issues/3732)
- [ ]  [ClientSupervisor](https://github.com/OpenMined/PySyft/issues/3738)
- [x]  [ObjectStore](https://github.com/OpenMined/PySyft/issues/3739)
  - [x]  [InMemoryObjectStore](https://github.com/OpenMined/PySyft/issues/3740)
  - [x]  [DiskObjectStore](https://github.com/OpenMined/PySyft/issues/3785)
- [x]  [StoreableObject](https://github.com/OpenMined/PySyft/issues/3741)
- [x]  [Action](https://github.com/OpenMined/PySyft/issues/3742)
  - [x]  [ImmediateActionWithReply](https://github.com/OpenMined/PySyft/issues/3743)
    - [x]  [ReturnObjectAction](https://github.com/OpenMined/PySyft/issues/3747)
  - [x] ImmediateActionWithoutReply
    - [x]  [ClassConstructorAction](https://github.com/OpenMined/PySyft/issues/3744)
    - [x]  [ModuleFunctionAction](https://github.com/OpenMined/PySyft/issues/3745)
    - [x]  [ObjectMethodAction](https://github.com/OpenMined/PySyft/issues/3746)
    - [x]  [SendObjectAction](https://github.com/OpenMined/PySyft/issues/3748)
    - [x]  [SaveObjectAction](https://github.com/OpenMined/PySyft/issues/3749)
  - [x]  [EventualActionWithoutReply](https://github.com/OpenMined/PySyft/issues/3750)
    - [x]  [GarbageCollectAction](https://github.com/OpenMined/PySyft/issues/3751)
    - [ ]  [MoveToDiskAction](https://github.com/OpenMined/PySyft/issues/3752)
- [x]  [Message](https://github.com/OpenMined/PySyft/issues/3753)
  - [x] MessageWithReply
  - [x] MessageWithoutReply
  - [x]  [RunActionMessage](https://github.com/OpenMined/PySyft/issues/3754)
  - [x]  [SearchMessage](https://github.com/OpenMined/PySyft/issues/3755)
  - [ ] [GossipMessage](https://github.com/OpenMined/PySyft/issues/3730)
- [x] [Pointer](https://github.com/OpenMined/PySyft/issues/3756)
- [ ] Plan Prototype
- [ ] Protocol Prototype
  - [ ] Role
     - [ ] role_id
     - [ ] pipes - dict of pipe objects
  - [ ] Execution
    - [ ] _execution_id.... points to args[0].execution_id
    - [ ] kwargs = [dict of ExecutionArgument objects]
  - [ ] Pipe
    - [ ] pipe_id
    - [ ] Action - __add__... which blocks for 2 tensor.
    - [ ] pending_executions - list of Execution objects which don't yet have all of their ExecutionArguments
    - [ ] output kwarg -> ExecutionArgument
  - [ ] ExecutionArgument
    - [ ] Object
    - [ ] execution_id
    - [ ] worker_id
    - [ ] pipe_id
    - [ ] pipe_kwarg_id
  - [ ] If you send to a worker an "Object wrapped in an ExecutionArgument" - this execution means that it's an input to a pipe
- [ ] Job Prototype
- [ ] [ThreadWorker and Async Support](https://github.com/OpenMined/PySyft/issues/3777)
- [ ] Pipeline
- [ ] NLP Objects Support (Tokenizer, Annotations, etc.)
- [ ] [Aries Abstractions](https://github.com/OpenMined/PySyft/issues/3811)

Note that this Epic does NOT necessarily include any work on object serde, framework support, asynchronous execution, threading, sophisticated security policies, or messaging over any network (everything is just about virtual worker objects).

## Who else?
This epic will be primarily worked on by @OpenMined/syft-core, but the abstractions we choose will impact many projects, especially @OpenMined/grid regarding how we do slow/fast object stores and search. However, @OpenMined/product, @OpenMined/natural-language-processing, and @OpenMined/security-and-identity should also be generally aware of what we're doing, but their direct involvement will be most needed in other epics within this milestone moreso than this one.

**Comment by madhavajay** [comment]
Remaining tasks on this issue should be converted into new tickets for the future backlog.
