### ISSUE TITLE
0.3.0 EPIC 4: Duet MVP

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3699]
## Description
Following the successful early demo of Duet at PriCon 2020, we will complete a number of remaining tasks to achieve the 0.3.0 release that will provide the anticipated functionality which can leverage GridNetwork to directly connect PySyft runtimes (such as runtimes within two separate jupyter notebooks) via peer-to-peer webrtc connection and allow training of a selection of PyTorch examples.

## Why?
This demo has already been established within our community as the MVP use of PySyft and PyGrid because it has both robust security and universal flexibility based on only simple remote execution.

## Breakdown
This epic can be broken into the following issues. Note that most of these already exist in the current version of PySyft and the code should be transferrable with (hopefully) minimal refactor.

- [x] Permissions: https://github.com/OpenMined/PySyft/issues/3963
- [x] sy.grid.connect()
- [x] my_worker.connect("another worker")
- [x] my_worker.send(x_tensor, searchable=True)
- [x] LIve-updating status visualization

**Comment by madhavajay** [comment]
This is essentially done, the remaining related tasks are being triaged through the GitHub Kanban board.
