### ISSUE TITLE
Initial Project Setup / Standards

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3720]
## Feature Description
In this issue - we want to discuss, establish, and implement a new and improved set of project standards for the PySyft project. This is the place to consider, "would it have been nice if PySyft was architected like <x> but goodness that'd be a lot of work to change it now." Things like type checking, various automated testing tools, automatic documentation (from the start), and coding style standards.

Just to keep this discussion organized, if you have a new proposed standard please comment with a Github issue and I'll add it to the list. 
- [x] [Setup v0.3.0 branch]()

Python Specific Requirements:
- [x] [PyScaffold for Initial project](https://github.com/OpenMined/PySyft/issues/3721)
- [x] [Automatic type-checking of Python type hints](https://github.com/OpenMined/PySyft/issues/3722)
- [x] [Discussion: Should we support Python <3.8?](https://github.com/OpenMined/PySyft/issues/3826)
- [x] [Automatic documentation from the start (with minimum "mergable" standards!)](https://github.com/OpenMined/PySyft/issues/3723)
- [ ] [Add OpenCollective to pip install?](https://github.com/OpenMined/PySyft/issues/3724)
- [ ] [100% test coverage requirement](https://github.com/OpenMined/PySyft/issues/3726)
- [ ] [Automatically tested (travis), multi-language support for example notebooks](https://github.com/OpenMined/PySyft/issues/3727)
- [x] [Framework Specific Tests for Syft](https://github.com/OpenMined/PySyft/issues/3761)

**Comment by shankarj67** [comment]
Can I help you with this issue?

**Comment by iamtrask** [comment]
Sure - take a stab at https://github.com/OpenMined/PySyft/issues/3724

**Comment by madhavajay** [comment]
This is complete and the three remaining tasks will be moved into new EPICs.
