### ISSUE TITLE
Worker

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3728]
## Feature Description
This Epic captures Issues to be done to define an abstract worker class called "Worker" which is currently defined [here](https://github.com/OpenMined/PySyft/blob/syft_0.3.0/src/syft/worker/worker.py#L15). I am making this an Epic because we will very likely update Worker multiple times between now and when it's done, so we can link issues to this Epic as needed.

The primary role of the Worker class is to define functionality necessary to route a message which a worker receives to the appropriate functionality to process said message. A worker should NOT be tied to a specific protocol for sending messages (such as HTTPS, WebRTC, WebSockets, etc.). Instead, the Worker class's purpose is to be sub-classed by other workers which do include functionality for receiving messages in a particular way. 

Furthermore, the long-term role of a Worker class is NOT to process the message directly but to instead deserialize and redirect the message to the appropriate WorkerService, which at the time of writing this issue is a hypothetical class which has not yet been written about or prototyped. My general thinking on the subject is merely that we don't want worker to become a "Megaclass" with thousands of lines of code for how to process every type of message. Furthermore, we do not want to require every worker to always have to run every service, although it is not yet clear when a worker type would only run a subset of services, this issue has come up in the past from time to time.

So, the list below includes all written plans for molding the Worker class from what it is today to what it needs to become in the future. This list will likely continue to be extended until Syft 0.3.0 is finally meged.

- [ ] Add documentation to the class. Make sure it presents well in sphinx.
- [ ] Create a WorkerService class and move all Worker.process_* methods
- [ ] Create required _send_msg and  _recv_msg methods which raise NotImplementedError
- [ ]  [WorkerSupervisor](https://github.com/OpenMined/PySyft/issues/3733)
  - [ ]  [MessageStatisticsLogger](https://github.com/OpenMined/PySyft/issues/3734)
  - [ ]  [MemoryLimitPolicy](https://github.com/OpenMined/PySyft/issues/3735)
  - [ ]  [MessageRateLimitPolicy](https://github.com/OpenMined/PySyft/issues/new?assignees=&labels=Type%3A+Epic+%3Acall_me_hand%3A&template=epic.md&title=)
- [ ]  [WorkerGuard](https://github.com/OpenMined/PySyft/issues/3737)
- [ ] Stub "known_worker" dictionary (BLOCKED BY: [Client](https://github.com/OpenMined/PySyft/issues/3729))
  - [ ] stub "add known worker" method
  - [ ] stub "share worker with worker" functionality using [GossipMessage](https://github.com/OpenMined/PySyft/issues/3730)
  - [ ] stub "Request known workers" including using using [GossipMessage](https://github.com/OpenMined/PySyft/issues/3730)
  - [ ] Discuss: How much should workers reveal the list of the workers they know to other workers?
- [ ] Write "GetInfo" to return info about worker
- [ ] Finalize documentation. Is it sufficient for a noob dev? Does it present well in Sphinx?

**Comment by tudorcebere** [comment]
I'll start tackling stuff around this one.
