### ISSUE TITLE
Device

### ISSUE THREAD

**Issue by iamtrask** [OpenMined/PySyft#3866]
## Description
In this Issue, we're going to define the schema, methods, messages, services, and client that all devices will have.

## Why?
This is important because we want to have a consistent API for executing code on devices, for managing their limited resources (compute, ram, and specialized/GPU compute). 

## Breakdown
Provide a bulleted or numbered list of how you might break this epic down into smaller issues.

- [ ] [Define Device Attributes](https://github.com/OpenMined/PySyft/issues/3867)
- [ ] Register Device with Domain
- [ ] Device Service: VM Lifecycle
- [ ] Device Service: VM Message Router
- [ ] Device Supervisor: manages and restricts the use of various device services (globally) using policies

## Who else?
Does this work affect any other repositories, projects, or teams? If so, [provide links to the repos and teams you'll be involving](https://github.blog/2012-05-09-introducing-team-mentions/).
