### ISSUE TITLE
Benchmark FPT/AST with the different types of approximations

### ISSUE THREAD

**Issue by gmuraru** [OpenMined/PySyft#3997]
## Description
We have different approximations in the FPT (FixedPrecisionTensor) for specific functions and also different protocols (```fss``` and ```securenn```) for operations on AST (AdditiveSharingTensor).

This ticket is an umbrella ticket to keep track of all the benchmarking operations.

Each sub-issue should have a graph/notebook (that has the graphs) where we track the performance of our SMPC components.
Those graphs and the benchmark script should be placed under ```syft/frameworks/torch/mpc/benchmarks```

## Why?
To have a clear view of how much improvement we get by using the approximations (and maybe how much accuracy we lose if we train a model using those approximations). 

## Breakdown
 * [x] [Benchmark Sigmoid](https://github.com/OpenMined/PySyft/issues/3998)
 * [x] [Benchmark Tanh](https://github.com/OpenMined/PySyft/issues/3999)
 * [x] [Benchmark AST operations for different protocols](https://github.com/OpenMined/PySyft/issues/4000)
 * [ ] [Benchmark Normal Training vs SMPC Training - using the approx methods](https://github.com/OpenMined/PySyft/issues/4001)
 * [ ] [Benchmark Normal Inference vs SMPC Inference - using the approx methods](https://github.com/OpenMined/PySyft/issues/4002)
*  [x] [Move to a framework and continuous benchmarking](https://github.com/OpenMined/PySyft/issues/4024)
