### ISSUE TITLE
Support Secure MPC

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4845]
## Description
This ticket relates to implementing some kind of MVP for Secure MPC integration for educational purposes. Due to the unique aspects of SPMC this might require some modifications of Syft itself.

## Definition of Done
A notebook is created in examples/smpc or something similar which demonstrates how SPMC could be used with Duet sufficiently to achieve the educational goals.

## Contacts
- @madhavajay
- @gmuraru 

## TODO
- [x] Initial Hello World Duet Notebooks
- [x] Support LMW (🐧🍎💠)
- [ ] Support 100% of SyMPC API
- [x] Update Syft to allow SyMPC with torch>=1.6.0

**Comment by madhavajay** [comment]
Related: 
https://github.com/OpenMined/PySyft/issues/4835
https://github.com/OpenMined/PySyft/pull/4823

**Comment by gmuraru** [comment]
@madhavajay we can close this, right?
