### ISSUE TITLE
Support Homomorphic Encryption

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4846]
## Description
This ticket relates to implementing some kind of MVP for Homomorphic Encryption integration for educational purposes for the 0.4.0 Milestone.

## Definition of Done
A notebook is created in examples/homomorphic-encryption or something similar which demonstrates how HE could be used with Duet sufficiently to achieve the educational goals.

## Contacts
- @madhavajay
- @youben11 
- @bcebere 

## TODO
- [x] Initial Hello World Duet Notebooks
- [x] Support LMW (🐧🍎💠)
- [x] Serialization and Deserialization of all types
- [x] Fix issue with Context required for deserialization of Vectors
- [x] Support @property setters in Syft - https://github.com/OpenMined/PySyft/issues/4918
- [x] Support the Enum tenseal.SCHEME_TYPE's in Syft - https://github.com/OpenMined/PySyft/issues/4919
- [x] Support 100% of TenSEAL API
- [x] Flesh out Notebook Examples

**Comment by madhavajay** [comment]
Related PR: https://github.com/OpenMined/PySyft/pull/4853/files

**Comment by madhavajay** [comment]
This is doneskis. ❤️
