### ISSUE TITLE
Support Secure Cloud Enclaves

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4849]
## Description

This ticket relates to adding support for Intel SGX Secure Enclave support for the 0.4.0 Milestone.
> https://aws.amazon.com/ec2/nitro/nitro-enclaves/

## Contacts
@madhavajay
@Benardi

## TODO
- [x] Spin up DCsv2 instance on Azure
- [x] Test SCONE containers on real DCsv2 hardware
- [ ] Test Syft inside SCONE container - https://github.com/OpenMined/PySyft/issues/4922
- [ ] Streamline Docker Containers
- [ ] Create Example Python Script for Secure Secret Exchange that Duet can connect to
- [ ] Create Ansible / Terraform script to setup and deploy everything to fresh Ubuntu 18 Azure instance
- [ ] Support LW (🐧💠)

## Future Scope
> https://azure.microsoft.com/en-us/solutions/confidential-compute/
> https://cloud.google.com/blog/products/identity-security/introducing-google-cloud-confidential-computing-with-confidential-vms

## Definition of Done
Example of SCONE SGX secret shared over Duet available in a Notebook.
README.md with instructions on how to deploy and run the example on Azure.
