### ISSUE TITLE
Support Zero-knowledge Proofs

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4850]
## Description
This ticket relates to implementing some kind of MVP for Zero-knowledge proofs integration for educational purposes for the 0.4.0 Milestone.

## Contacts
- @madhavajay

The library for this will be:
https://github.com/spring-epfl/zksk

## TODO
- [ ] Initial Hello World Notebooks
- [x] Serialization and Deserialization of ZKP types
- [ ] 100% of API in AST
- [x] LMW support
- [ ] Flesh out Notebook Examples

## Definition of Done
A notebook is created in examples/zero-knowledge-proofs or something similar which demonstrates how ZKP could be used with Duet sufficiently to achieve the educational goals.

**Comment by Param-29** [comment]
I'd like to work on this issue.
