### ISSUE TITLE
Private AI Series Library Support

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#4883]
## Description
We require support for a number of libraries to cover the listed educational units below.

## Why?
To facilitate the Private AI Series.

## Breakdown

- [ ] Support Public Key Technology: https://github.com/OpenMined/PySyft/issues/4844
- [ ] Support Secure MPC: https://github.com/OpenMined/PySyft/issues/4845
- [x] Support Homomorphic Encryption: https://github.com/OpenMined/PySyft/issues/4846
- [ ] Support Functional Encryption: https://github.com/OpenMined/PySyft/issues/4847
- [ ] Support Private Set Intersection: https://github.com/OpenMined/PySyft/issues/4848
- [ ] Support Zero-knowledge Proofs: https://github.com/OpenMined/PySyft/issues/4850
- [ ] Support Differential Privacy: https://github.com/OpenMined/PySyft/issues/4851
- [ ] Support Secure Cloud Enclaves: https://github.com/OpenMined/PySyft/issues/4849
- [ ] Support Split NNs: https://github.com/OpenMined/PySyft/issues/5204

## Platform Support
The goal is full support, but let's see where we can get to.
Python | Linux | Mac | Windows
--- | --- | --- | ---
3.6 | ✅ | ✅ | ✅
3.7 | ✅ | ✅ | ✅
3.8 | ✅ | ✅ | ✅

**Comment by gmuraru** [comment]
@madhavajay and also mark SMPC here
