### ISSUE TITLE
Templated Collections

### ISSUE THREAD

**Issue by tudorcebere** [OpenMined/PySyft#5062]
## Description
Our data structures currently work in the remote scenario, using most of the API the right way. A blocker appears when you want to retrieve information from that collection. Examples:

```
remote_client.syft.lib.python.List([1, 2, 3]).__getitem__(0) # AnyPtr
remote_client.syft.lib.python.Dict({"1": 1}).__getitem__("1") #AnyPtr
```
The `AnyPtr` and the `Any` object are minimal objects. We want to extend these types in the AST with templates, for example, let's assume we have a global variable `two_ints` in a fictional `test_module` that we know it will always return a tuple of two ints.

This is how we add currently in the AST:
```
allowlist["test_module.two_ints"] = "syft.lib.python.Tuple"
```

```
tuple_ptr = remote_client.test_module.two_ints
item_one = tuple_ptr[0] # AnyPtr <- rather useless
item_two = tuple_ptr[1] # AnyPtr <- rather useless
```
We would like to change this to the following API:
```
allowlist["test_module.two_ints"] = syft.lib.python.Tuple[syft.lib.python.Int, syft.lib.python.Int]
```

And then the usage would be

```
tuple_ptr = remote_client.test_module.two_ints
item_one = tuple_ptr[0] # IntPtr <- complete information
item_two = tuple_ptr[1] # IntPtr <- complete information
```
Even more, we would like to enforce type checking, for example, if the right types are not retrieved/added, an error should be thrown.

## Why?
Currently, collections are not useful if you want to manipulate data inside them one element at a time. This has an impact on `torch.DataLoader`, dicts and so on.

## Breakdown
This issue will be solved when the following data structures have the described functionality:
* Create Templated Iterator:
- [ ] Create the `Iterator` metaclass
- [ ] Confirm that Iterator[Any] will produce the same results as the current `Iterator`.
- [ ] Add support for any combination of types.
- [ ] Add tests (include tests with Union types as well!).
- [ ] Write docs on it.

* Create Templated Tuple
- [ ] Create the `Tuple` metaclass.
- [ ] Add the uniform method on the metaclass, that will generate a tuple type that can have any number of elements, but only a specified type, e.g.: `Tuple.uniform[Int]`.
- [ ] Confirm that Tuple.uniform[Any] will produce the same results as the current `Tuple`.
- [ ] Add support for an exact number of parameters, for example, Tuple[Int, Float, Double].
- [ ] Add tests (include tests with Union types as well!).
- [ ] Write docs on it.

* Create Templated List:
- [ ] Create the `List` metaclass
- [ ] Confirm that List[Any] will produce the same results as the current `List`.
- [ ] Add support for any combination of types.
- [ ] Add tests (include tests with Union types as well!).
- [ ] Write docs on it.

* Create Templated Dict:
- [ ] Create the `Dict` metaclass
- [ ] Confirm that Dict[Any, Any] will produce the same results as the current `Dict`, where the first type is the types of Keys and the second one is the types of Values.
- [ ] Add support for any combination of types.
- [ ] Add tests (include tests with Union types as well!).
- [ ] Write docs on it.

* Create Templated OrderedDict:
- [ ] Create the `OrderedDict` metaclass
- [ ] Confirm that OrderedDict[Any, Any] will produce the same results as the current `OrderedDict`, where the first type is the types of Keys and the second one is the types of Values.
- [ ] Add support for any combination of types.
- [ ] Add tests (include tests with Union types as well!).
- [ ] Write docs on it.

## Who is going to work on this?
@tudorcebere 
@nahuakang

## Additional Context
I will provide an example of how this should be done on `Iterators`.

**Comment by madhavajay** [comment]
Can we get a Numeric type which is used in most cases for Collections seeing as there should be a lot of instances where that will be the case.
