### ISSUE TITLE
Opacus

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5103]
## Description
See: https://github.com/OpenMined/PySyft/pull/5165

## TODO
- [x] Added workaround to cast numpy floats and ints to python
- [x] Fixed return type on opacus get_privacy_spent
- [x] Refactor dynamic method resolution
- [x] Fix SyModule with PrivacyEngine
       Init method is expecting object or pointer but we have neither
       Perhaps we could create a fake top level module on the remote side and get a pointer to it?
- [x] Add Integration Test Checkpoints to notebooks

**Comment by madhavajay** [comment]
The epsilon is fixed, this was related to a change in Lists vs Tuples and also the return of numpy types on the Opacus side.
