### ISSUE TITLE
Create Mechanism to Test Duet Notebooks

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5114]
## Description
We want to be able to run our DO / DS notebooks as tests. Naturally this presents a few issues as they are two different processes and they require the ability to programmatically pause at certain steps to allow the other side of the Duet connection to perform some actions.

Now that Duet Integration tests are solved the next step would be to introduce some mechanism to allow pausing between notebooks possibly with a simple `time.sleep`.

We can introduce a custom Comment which can be placed in notebooks that gets interpreted by our testing code such as:
```
# integration_test_sleep=3
```

Combining this with the existing notebook to python conversion setup we have here we should be able to automatically convert notebooks to Integration Tests and then run them.
```
./scripts/nb_test.sh
pytest examples/api -n auto --no-cov
```

## Tasks
- [x] Update Script for Converting Notebooks to Tests
- [x] Add and Parse Special Barrier / Wait commands
- [x] Add Asserts to Notebook
- [x] Update CI yaml to run these tests

More context in this slack discussion: https://openmined.slack.com/archives/G0186Q3EAHL/p1612505839315300

We should start with something like this where the notebook works and the moments to checkpoint are well defined.
https://github.com/OpenMined/PySyft/blob/dev/examples/homomorphic-encryption/Tutorial_0_TenSEAL_Syft_Data_Owner.ipynb
https://github.com/OpenMined/PySyft/blob/dev/examples/homomorphic-encryption/Tutorial_0_TenSEAL_Syft_Data_Scientist.ipynb

## Definition of Done
CI has a separate step which generates and runs this first Integration Test from the above two notebooks and the test passes.

**Comment by bcebere** [comment]
I can work on this one, please assign it to me.
