### ISSUE TITLE
PyGrid End-to-End Integration Test

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5166]
## Description
We want to create an end to end PyGrid Integration test that does HE Inference from these example notebooks:
https://github.com/OpenMined/PySyft/tree/dev/examples/homomorphic-encryption

- Starts a PyGrid Domain
- Builds a Worker Container
- Starts a Worker Container
- Loads model and weights on Worker
- Starts a Duet process and connects
- Loads an image and encrypts it
- Sends image for inference
- Gets result

## TODO
- [ ] Setup AWS Github CI Runners https://github.com/OpenMined/PySyft/issues/5181
- [ ] Create an Integration test that starts all these parts and sends a test message
- [ ] Add the HE Demo to the test

## Definition of Done
Integration tests are run through GitHub CI when code changes in Syft and pass.
We might want to limit it to certain branch names or users who can initiate these tests.
