### ISSUE TITLE
Improve Plans

### ISSUE THREAD

**Issue by madhavajay** [OpenMined/PySyft#5541]
## Description
As discussed we want to do the following to improve Plans:
- [ ] shape inference, improve ability to define input shapes and detect them during building or execution
- [ ] performance, remove need to sign and serde just to trace actions
- [ ] local execution, improve symmetry between local and remote execution
- [ ] model.to_symodule(), determine better naming and between PlanModules and PointerModules

## Definition of Done
Individual issues dealt with in their own tickets.
